/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p56.reto4.vista;

/**
 *
 * @author Nata_Rosero
 */
public class VentanaMenuReq extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenuReq
     */

    public VentanaMenuReq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        optRequerimiento1 = new javax.swing.JRadioButton();
        optRequerimiento2 = new javax.swing.JRadioButton();
        optRequerimiento3 = new javax.swing.JRadioButton();
        consultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("    Consultas P&C Proyectos y Construcciones");
        setBackground(new java.awt.Color(255, 255, 255));

        optRequerimiento1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(optRequerimiento1);
        optRequerimiento1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        optRequerimiento1.setText("Requerimiento 1");
        optRequerimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRequerimiento1ActionPerformed(evt);
            }
        });

        optRequerimiento2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(optRequerimiento2);
        optRequerimiento2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        optRequerimiento2.setText("Requerimiento 2");

        optRequerimiento3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(optRequerimiento3);
        optRequerimiento3.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        optRequerimiento3.setText("Requerimiento 3");

        consultar.setBackground(new java.awt.Color(204, 204, 204));
        consultar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("  ¡Buenas tardes!");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Selecciona el requerimiento que deseas consultar.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(optRequerimiento1)
                        .addGap(39, 39, 39)
                        .addComponent(optRequerimiento2)
                        .addGap(43, 43, 43)
                        .addComponent(optRequerimiento3)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(consultar)
                        .addGap(208, 208, 208))))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optRequerimiento1)
                    .addComponent(optRequerimiento2)
                    .addComponent(optRequerimiento3))
                .addGap(18, 18, 18)
                .addComponent(consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optRequerimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRequerimiento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optRequerimiento1ActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed

        if (optRequerimiento1.isSelected()){;
            VentanaR1 vl = new VentanaR1();
            vl.setVisible(true);
            vl.generarTabla();
        } if (optRequerimiento2.isSelected()){;
            VentanaR2 vl = new VentanaR2();
            vl.setVisible(true);
            vl.generarTabla();
        } if  (optRequerimiento3.isSelected()){;
            VentanaR3 vl = new VentanaR3();
            vl.setVisible(true);
            vl.generarTabla();
        }

    
    }//GEN-LAST:event_consultarActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton optRequerimiento1;
    private javax.swing.JRadioButton optRequerimiento2;
    private javax.swing.JRadioButton optRequerimiento3;
    // End of variables declaration//GEN-END:variables
}
